#!/usr/bin/env bash
# Installs Nginx server and redirects /redirect_me to another page

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/youssefelghamour permanent;/" /etc/nginx/sites-available/default

service nginx restart
