#!/usr/bin/env bash
# Installs Nginx server and redirects /redirect_me to another page

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/youssefelghamour permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default

service nginx restart
