#!/usr/bin/env bash
# Script that install and configure HAproxy on the lb-01 server

# Set non-interactive mode for apt-get to avoid prompts during installation
export DEBIAN_FRONTEND=noninteractive

apt-get -y update

apt-get -y install haproxy

# Create a backup of the original HAProxy configuration
mv /etc/haproxy/haproxy.cfg{,.original}

# Configure HAProxy with a new frontend and backend
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-servers\n\nbackend web-servers\n\tbalance roundrobin\n\tmode http\n\tserver 511149-web-01 18.204.9.11:80 check\n\tserver 511149-web-02 18.233.66.83:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
