#!/usr/bin/env bash
# configures Nginx to listen on port 80
sed -i 's/ipv6only=on//' /etc/nginx/sites-available/default
sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
nginx -s reload
