#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache
sudo -u nginx service nginx restart
